"""Download upstream datasets into data/raw and record their provenance.

Usage: python pipeline/01_fetch.py [--force]
"""

import argparse
import datetime as dt
import hashlib
import zipfile

import requests

from config import DATASETS, RAW


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def fetch(key, meta, force=False):
    dest_dir = RAW / key
    dest_dir.mkdir(parents=True, exist_ok=True)
    archive = dest_dir / meta["url"].rsplit("/", 1)[-1]

    if force or not archive.exists():
        print(f"Downloading {meta['title']} ...")
        resp = requests.get(meta["url"], timeout=120)
        resp.raise_for_status()
        archive.write_bytes(resp.content)
    else:
        print(f"Using cached {archive.relative_to(RAW)}")

    with zipfile.ZipFile(archive) as z:
        z.extractall(dest_dir)

    return {
        "file": archive.relative_to(RAW).as_posix(),
        "sha256": sha256(archive),
        "bytes": archive.stat().st_size,
        "accessed": dt.date.fromtimestamp(archive.stat().st_mtime).isoformat(),
    }


def write_sources(records):
    lines = [
        "# Raw data sources",
        "",
        "Generated by `pipeline/01_fetch.py`. The files themselves are gitignored;",
        "run the script to download them. Checksums let you confirm you have the same versions.",
        "",
    ]
    for key, meta in DATASETS.items():
        r = records[key]
        lines += [
            f"## {meta['title']}",
            "",
            f"- **Download:** {meta['url']}",
            f"- **Homepage:** {meta['homepage']}",
            f"- **Licence:** {meta['licence']}",
            f"- **Citation:** {meta['citation']}",
            f"- **Local file:** `data/raw/{r['file']}` ({r['bytes']:,} bytes)",
            f"- **SHA-256:** `{r['sha256']}`",
            f"- **Accessed:** {r['accessed']}",
            "",
        ]
    (RAW / "SOURCES.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true", help="re-download even if cached")
    args = parser.parse_args()

    records = {key: fetch(key, meta, args.force) for key, meta in DATASETS.items()}
    write_sources(records)
    print(f"Wrote {RAW / 'SOURCES.md'}")


if __name__ == "__main__":
    main()
